- name: Install microk8s
  become: yes
  hosts: microk8s
  tasks:
    - community.general.snap:
        classic: true
        channel: 1.26
        name:
          - microk8s

- name: Adding user to group
  become: yes
  hosts: microk8s
  tasks:
    - user:
        name: root
        groups: microk8s
        append: yes
    - meta: reset_connection

- name: Change kube folder ownership
  become: yes
  hosts: microk8s
  tasks:
    - file:
        path: /home/root/.kube
        owner: root
        group: root
        state: directory

- name: Enable microk8s common modules
  hosts: microk8s
  tasks:
    - command: microk8s enable dns cert-manager metrics-server